### ISSUE TITLE
Oregon Trail doesn't boot

### ISSUE THREAD

**Issue by DFL1973** [gyurco/apple2efpga#1]
Tried all the available RBFs and some different Oregon Trail images that I found. 
Doesn't work for me.

**Comment by gyurco** [comment]
I have a WildWest-Alamo-GodRush-WestwardHo-OregonTrail.dsk, it works (after converting it to NIB of course).

**Comment by DFL1973** [comment]
It´s not the same game.
But, when I was looking around to point you to the correct game, I found a set that works for me.
http://www.mecc.co/software/apple-ii/the-oregon-trail---a-157/
Thanks!
